services:
  Elbformat\IbexaIconFieldtype\FieldType\Icon\Type:
    arguments:
      $serializer: '@eZ\Publish\SPI\FieldType\ValueSerializerInterface'
      $validator: '@Symfony\Component\Validator\Validator\ValidatorInterface'
    tags:
      - { name: ezplatform.field_type, alias: icon }
      - { name: ezplatform.field_type.form_mapper.value, fieldType: icon }

  Elbformat\IbexaIconFieldtype\FieldType\Icon\SearchField:
    class: '%ezpublish.fieldType.indexable.unindexed.class%'
    tags:
      - { name: ezplatform.field_type.indexable, alias: icon }